== 3. Cons, the Magnificent

To create `rember`, the fist thing we ask is `(null? lat)` because it is the first commandment.

=== function: `rember'

.`rember' function definition (incorrect)
[source,scheme,lineos]
----
;; Atom (list-of Atom) -> (list-of Atom)
;; Produce list of atoms with first occurrence of `a' removed.
;; If `a' doesn't exist in `lat', produce the unmodified list.

(define rember
  (lambda (a lat)
   (cond
    ((null? lat) '())
    ((eq? (car lat) a) (cdr lat)) ; <1>
    (else
     (cons (car lat) (rember a (cdr lat))))))) ; <2>

(test-group "`rember':"
        (test "element should be removed from beginning of lat"
              '(y z x)
              (rember 'x '(x y z x)))
        (test "element should be removed from middle of lat"
              '(x z)
              (rember 'y '(x z)))
        (test "element should be removed from end of lat"
              '(x y)
              (rember 'z '(x y z))))
----

1. Note that we *do not recur* here. This is what allows `rember` to remove only the first occurrence of `a` in `lat`.
2. Yes, here we recur to check if `a` is in the rest of `lat`.

Also note that we *do not use `cons' in this function*.

----
(rember 'x '(x y z))
;; →  (y z), looks ok.

(rember 'x '(a b c y x z))
;; →  (z), oops!
----

Since we did not use cons to keep elements that should not be removed, we lost them and got an incorrect result. We dropped `'x`, but we also lost all atoms preceding `'x`.

So, we use Cons, The Magnificent:

=== function: `rember' (correct version)

.`rember' function definition (correct this time)
[source,scheme,lineos]
----
include::./definitions.scm[tag=rember]
----

1. Now we use `cons` to keep elements that should not be removed.

=== The Second Commandment

[NOTE,caption=COMMANDMENT]
====
Use `cons` to build lists.
====

=== function: `firsts'

.`firsts' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=firsts]
----


=== The Third Commandment

[NOTE,caption=COMMANDMENT]
====
When building a list, describe the first tipical element, and then `cons` it into the natural recursion.
====

Remember: we always ask two questions about a `lat`: `(null? lat)` and `else`.

=== function: `insertR'

.`insertR' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=insertR]
----

=== function: `insertL'

.`insertL' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=insertL]
----


Note that

[source,scheme,lineos]
----
(cons new
      (cons (car lat)
            (cdr lat)))
----

Is just the same as

[source,scheme,lineos]
----
(cons new lat)
----

=== function: `subst'

.`subst' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=subst]
----


=== function: `subst2'

.`subst2' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=subst2]
----


=== function: `multirember'

.`multirember' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=multirember]
----

Note the difference from this version that removes all occurrences to the `rember`, that removes just the first occurrence of `a` in `lat`:

.excerpt of the functions `multirember' and `rember'
[source,scheme,lineos]
----
;; `multirember' removes `a' “globally” in `lat'.
((eq? (car lat) a)
 (multirember a (cdr lat))) ; <1>

;; `rember' removes only the first occurrence of `a` in `lat'.
((eq? (car lat) a)
 (cdr lat)) ; <1>
----

1. We recur, that is, we keep looking for further occurrences of `a` in `lat` and keep ignoring/dropping them.
2. Just return the rest of `lat`, therefore not looking for any other occurrences of `a` in `lat`.


=== function: `multiinsertR'

.`multiinsertR' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=multiinsertR]
----


=== function: `multiinsertL'

.`multiinsertL' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=multiinsertL]
----



++++
<style type="text/css">
code {
    font-family: 'Noto Mono Regular', 'Ubuntu Mono', 'Droid Sans Mono';
}
.listingblock .pygments .tok-c1 {
    font-style: normal;
}
</style>
++++

