== 3. Cons, the Magnificent

To create `rember`, the fist thing we ask is `(null? lat)` because it is the first commandment.

===  rember v1

.`rember' function definition 
[source,scheme]
----
;;;;
;; rember :: Atom [Atom] -> [Atom]
;;
;; Removes the first occurrence of `a` in `lat`.
;;
(define rember
  (lambda (a lat)
    (cond
     ((null? lat) '())
     (else (cond
            ((eq? (car lat) a) (cdr lat)) ; <1>
            (else (cons (car lat) ; <2>
                        (rember a (cdr lat))))))))) ; <3>
----

1. Note that we *do not recur* here.
This is what allows `rember` to remove only the first occurrence of `a` in `lat`.

2. Use of `cons` to keep the elements we don't want to remove.

3. Recur to check if `a` is in the rest of `lat`.

We always ask two questions about a `lat`:

* `(null? lat)`
* `else`

===  rember v2

[source,scheme]
----
;;;;
;; rember :: Atom [Atom] -> [Atom]
;;
;; Removes the first occurrence of `a` in `lat`.
;;
(define rember
  (lambda (a lat)
    (cond
     ((null? lat) '())
     ((eq? (car lat) a) (cdr lat))
     (else (cons (car lat)
                 (rember a (cdr lat)))))))
----

===  firsts

[source,scheme]
----
;;;;
;; firsts :: [List] -> [List]
;;
;; Returns a list of all car's of the sublists.
;;
;; ASSUME: The input list is either an empty list or
;; a list composed of only non-empty lists. That is,
;; it is expected that we can `car` each sub-list.
;;
(define firsts
  (lambda (l)
    (cond
     ((null? l) '())
     (else
      (cons (car (car l))
            (firsts (cdr l)))))))
----

===  insertR

.insertR function definition
[source,scheme]
----
;;;;
;; insertR :: Atom Atom [Atom] -> [Atom]
;;
;; Inserts `new` to the right of `old`.
;;
;; ASSUME: `old` is a member of `lat`. If `old` is not a member
;; of `lat`, the unchanged list is returned.
;;
(define insertR
  (lambda (new old lat)
    (cond
     ((null? lat) '())
     ((eq? (car lat) old)
      (cons (car lat) (cons new (cdr lat)))) ; <1>
     (else
      (cons (car lat)
            (insertR new old (cdr lat)))))))
----

1. Because `(car lat)` is the the same value a `old`, we could do `(cons old (cons new (cdr lat)))` just as well.

===  `insertL'

.`insertL' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=insertL]
----


[source,scheme,lineos]
----
(cons new
      (cons (car lat)
            (cdr lat)))
----

Is just the same as

[source,scheme,lineos]
----
(cons new lat)
----

===  `subst'

.`subst' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=subst]
----


===  `subst2'

.`subst2' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=subst2]
----


===  `multirember'

.`multirember' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=multirember]
----

Note the difference from this version that removes all occurrences to the `rember`, that removes just the first occurrence of `a` in `lat`:

.excerpt of the functions `multirember' and `rember'
[source,scheme,lineos]
----
;; `multirember' removes `a' “globally” in `lat'.
((eq? (car lat) a)
 (multirember a (cdr lat))) ; <1>

;; `rember' removes only the first occurrence of `a` in `lat'.
((eq? (car lat) a)
 (cdr lat)) ; <1>
----

1. We recur, that is, we keep looking for further occurrences of `a` in `lat` and keep ignoring/dropping them.
2. Just return the rest of `lat`, therefore not looking for any other occurrences of `a` in `lat`.


===  `multiinsertR'

.`multiinsertR' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=multiinsertR]
----


===  `multiinsertL'

.`multiinsertL' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=multiinsertL]
----

See <<fourth-commandment-preliminary>>.


===  `multisubst'

.`multisubst' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=multisubst]
----

In short, besides the laws and commandments:

To do something only to the first occurrence:

----
(<some-operation> <car cat/new/old/etc> (cdr lat))
----

To do something in all occurrences:

----
(<some-operation> <car cat/new/old/etc>
  (recursive-invocation <params> (cdr lat)))
----

So, `(cdr lat)` vs `(recursive-function <params> `(cdr lat)`.


