== 4. Numbers Games

Numbers are atoms, but for this book we only consider non-negative numbers (Natural Set), and ignore negative and floating point numbers.

For this book `(sub1 0)` is a “no answer” thing, but it practice it would produce `-1`.


=== function: `o+'

.`o+' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=o+]
----

We broke the first commandment as we did not use `null?`. Still asking `zero?` of a number is somewhat like asking `null?` of a list.

`zero?` is like `null?` and `add1` (builds numbers) is like `cons` (builds lists).


=== function: `o-'

.`o-' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=o-]
----


A *tuple* is a list of numbers. `(3 (7 4) 13 9)` is not a tuple because it contains a list, that is, `(7 4)` is not a number.

`'()` is a tup. It is the empty tup.

The natural way to build numbers from list is to use `o+` instead of `cons`.

The value for the terminal condition for building lists with `cons` is `'()`. The value for terminal condition when building numbers with `o+` is `0`.

* terminal condition for a list: `(null? my-list)`.
** `+((null? my-list) '())+`
* terminal condition for a tup: `(null? my-tup)`.
** `((null? my-tup) 0)`, that is, `0` for adding/subtracting. `1` for multiplying (not sure (yet) about division).


A list is an empty list, or a list with an atom `(car my-list)` and `(cdr my-list)` is yet another list.

A tuple is an empty list, or a list with a number `(car my-tup)` and `(cdr my-tup)` which is yet another tup.

A number is either `zero` or it is one added to a “rest”, where rest is again a number.

The natural terminal condition for numbers is `(zero? n)`. The natural recursion on a number is `(sub1 n)` because we want to reach `0`.

See <<first-commandment-rev-1>>.

=== function: `addtup'

.`addtup' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=addtup]
----

See <<fourth-commandment-rev-1>>.


=== Note About Recursion

When we recur (not using tail-recursion), the recursive call is _never_ in the combination part. The combination part is always handled by some other operation, and the recursive invocation happens more at the end of the expression, generally involving `cdr` or `sub1`. Just take a look at the `else` question of our procedures and see the similarities.


=== function: `o*'

.`o*' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=o*]
----

See <<fifth-commandment>>.


=== function: `tup+'

.`tup+' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=tup+]
----


=== function: `tup+v2'

.`tup+v2' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=tup+v2]
----

In this version, if one tuple is lengthier than the other, we just `cons` the already produced sums onto the remaining list without doing any further `o+` operations.


=== function: `o>'

.`o>' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=o>]
----

1. The order of the questions matter. If we asked `(zero? m)` before `(zero? n)`, we would produce `#t` even for cases when both numbers are actually equal.


=== function: `o<'

.`o<' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=o<]
----

=== function: `o='

.`o=' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=o=]
----


=== function: `o**'

.`o**' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=o**]
----


=== function: `o/'

.`o/' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=o/]
----

=== function: `len'

.`len' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=len]
----


=== function: `pick'

.`pick' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=pick]
----

In `pick`, `(car lat)` is always in sync with `n`.


=== function: `rempick'

.`rempick' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=rempick]
----

=== About PRIMITIVES


Can you write `number?` which is true if its argument is a numeric atom and false if it is anthing else?

No: `number?`, like `add1`, `sub1`, `zero?`, `car`, `cdr`, `cons`, `null?`, `eq?`, and `atom?`, is a primitive function.


link:https://groups.google.com/forum/#!topic/comp.lang.scheme/1owCrv0H3lk[My question on comp.lang.scheme about primitives.]


=== function: `no-nums'

.`no-nums' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=no-nums]
----

=== function: `all-nums'

.`all-nums' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=all-nums]
----

Numbers are atoms. Still, we use `=` for numbers and `eq?' for all other atoms.


=== function: `eqan?'

.`eqan?' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=eqan?]
----

