== 5. \*Oh My Gawd*:, It's Full of Stars

=== rember*

.rember* function definition
[source,scheme]
----
;;;;
;; rember* :: Atom [a] -> [a]
;;
;; Returns `l` with all occurrences of `a` removed.
;;
(define rember*
  (lambda (a l)
    (cond
     ((null? l) '())
     ((atom? (car l))
      (cond
       ((eq? (car l) a)
        (rember* a (cdr l)))
       (else
        (cons (car l)
              (rember* a (cdr l))))))
     (else
      (cons (rember* a (car l))
            (rember* a (cdr l)))))))
----

=== insertR*

.insertR* function definition
[source,scheme]
----
;;;;
;; insertR* :: Atom [a] -> [a]
;;
;; Returns `lst` with `new` inserted to the right of all occurrences
;; of `old`.
;;
(define insertR*
  (lambda (new old lst)
    (cond
     ((null? lst) '())
     ((atom? (car lst))
      (cond
       ((eq? (car lst) old)
        (cons old
              (cons new
                    (insertR* new old (cdr lst)))))
       (else
        (cons (car lst)
              (insertR* new old (cdr lst))))))
     (else
      (cons (insertR* new old (car lst))
            (insertR* new old (cdr lst)))))))
----

See <<first-commandment-final-version>>.

Both `rember*` and `insertR*` recur with `car` as well when `car lst` itself happens to be a list (besides the usual recursion `cdr`).

All “star functions” work on lists that are either:

- empty
- an atom __cons__ed onto a list
- a list __cons__ed onto a list

=== `occur*'

.`occur*' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=occur*]
----

1. Note the use of `+` to combine the result of the two recursive invocations.

=== `subst*'

.`subst*' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=subst*]
----

1. Note that `cons` the result of one recursive invocation onto the result of the other recursive invocation.

Besides that, we keep recurring with both `car` and `cdr` in these _star_ functions.


=== `insertL*'

.`insertL*' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=insertL*]
----


=== `member*'

.`member*' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=member*]
----

Pay attention the use of `or` in the combination part of the `atom?` an `else` questions.


=== `leftmost'

.`leftmost' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=leftmost]
----

1. Since it is assumed `l' is not empty, it is not necessary to ask `(null? l)`.


=== `eqlist?'

Each argument may be either

- empty,
- an atom __cons__ed onto a list, or
- a list __cons__ed onto a list.

.`eqlist?' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=eqlist?]
----

1. If both are null, then we don't even get to the next question (`or`).
2. If we get to this question, then at least one of the above was not null (we used `and`) and if now one happens to be null (we are using `or`) then we know the lists are not equal.


=== `my-equal?'

.`my-equal?' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=my-equal?]
----

Note that we used `eqlist?` to define `my-equal?`.


=== `eqlist? (v2)'

.`eqlist? (v2)' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=eqlist?-v2]
----

See <<sixth-commandment>>.


=== `rember (v2)'

.`rember (v2)' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=rember-v2]
----



