== 5. \*Oh My Gawd*:, It's Full of Stars

=== function: `rember*'

.`rember*' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=rember*]
----


=== function: `insertR*'

.`insertR*' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=insertR*]
----

See <<first-commandment-final-version>>.

Both `rember*` and `insertR*` recur with `car` as well when it happens to be a list, as well as with the `cdr`.

All `*-functions' work on lists that are either:

- empty,
- an atom __cons__ed onto a list, or
- a list __cons__ed onto a list.

See <<fourth-commandment-final-version>>.


=== function: `occur*'

.`occur*' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=occur*]
----

1. Note the use of `+` to combine the result of the two recursive invocations.

=== function: `subst*'

.`subst*' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=subst*]
----

1. Note that `cons` the result of one recursive invocation onto the result of the other recursive invocation.

Besides that, we keep recurring with both `car` and `cdr` in these _star_ functions.


=== function: `insertL*'

.`insertL*' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=insertL*]
----


=== function: `member*'

.`member*' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=member*]
----





