== 6. Shadows

For this chapter, an arithmetic expression is either an atom (including numbers), i.e, `*` or `9`, or two expressions combined by `+`, `*` or `↑`, something like `9 + 1`.

`(quote +)` is the atom `+`, , not the operation `+`. The same holds true for other operators like `*`, `/`, etc.

`(n + 3)` is not an arithmetic expression because our earlier definition of arithmetic expression does not include parenthesis.

These is an invalid arithmetic expressions by our definition:

----
(3 + 5 * (2 + 3))
----

It should be like this instead:

----
(3 + (5 * (2 + 3)))
----

=== function: `numbered?'

.`numbered?' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=numbered?]
----

See <<seventh-commandment>>.


=== function: `value' (v1)'

.`value' (v1) function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=value-v1]
----

If we do `(cdr (cdr (+ 1 2)))` we get `(2)`, and that is not a sub-expression of our entire arithmetic expression; `2` would though, and `(car (cdr (cdr (+ 1 2))))` would be the proper way to access it. That is what we do in the next example as well.

=== function: `value' (v2)

.`value' (v2) function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=value-v2]
----


=== function: `1st-sub-exp'

.`1st-sub-exp' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=1st-sub-exp]
----


=== function: `2nd-sub-exp'

.`2nd-sub-exp' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=2nd-sub-exp]
----


=== function: `operator'

.`operator' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=operator]
----


=== function: `value' (v3)

.`value' (v3)' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=value-v3]
----

This version uses helper functions to access the operator and the sub-expressions.

We have by now used two syntaxes/representations for expressions, one where the operators are infix, and other where operators are prefix:

----
(1 + (2 + 3)) ; infix
(+ 1 (+ 2 3)) ; prefix (default in lisps).
----

Our function `value` uses the helper functions `1st-sub-exp`, `2nd-sub-exp` and `operator`. If we just change those helper functions, our `value` function can handle any of the two possible representations without changing the function `value` itself.

We have used representations for truth-values, numbers. 4 represents the concept of “four”, but we could have used `(() () () ())` as well, or `((((()))))` or even `IV`.

We use four primitives for numbers: `number?`, `zero?`, `add1` and `sub1`.

// NOTE: Escapes necessary or output gets some parenthesis missing.
- `()` is zero.
- `(())` is one.
- `\(() ())` is two.
- `\(() () ())` is three.
- and so on and so forth...


=== Alternative Number Representation

.An example of using `()` to represent numbers.
[source,scheme,lineos]
----
include::./definitions.scm[tag=our-lnums1]
----




