== 7. Friends and Relations

=== function: `set?'

.`set?' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=set?]
----


=== function: `makeset'

.`makeset' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=makeset]
----

=== function: `makeset' (v2)

.`makeset' (v2) function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=makeset-v2]
----

=== About Sets

A Set is an unordered collection of objects without duplicates.

Two sets are the same if they have the same members (which may be in different order).

A subset is a set in which its members are part of another set. Two equal sets also mean that one set is a subset of the other, and vice-versa.

Two sets intersect if they contain at least one common member.


=== function: `subset?'

.`subset?' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=subset?]
----


=== function: `eqset?'

.`eqset?' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=eqset?]
----


=== function: `intersect?'

.`intersect?' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=intersect?]
----

Note that `subset?` uses `and`, and `intersect?` uses `or`, otherwise they are the same thing.


=== function: `intersect'

.`intersect' function definition
[source,scheme,lineos]
----
include::./definitions.scm[tag=intersect]
----

