== » Commandments

[[first-commandment-preliminary]]
=== The First Commandment (preliminary)

[NOTE,caption=COMMANDMENT]
====
Always ask `null?` as the first question in expressing any function.
====

[[first-commandment-rev-1]]
=== The First Commandment (rev. 1)

[NOTE,caption=COMMANDMENT]
====
* When recurring on a list of atoms, `lat`, ask two questions about it: `(null? lat)` and `else`.
* When recurring on a number, `n`, ask two questions about it: `(zero? n)` and `else`.
====

[[first-commandment-final-version]]
=== The First Commandment (final version)

[NOTE,caption=COMMANDMENT]
====
* When recurring on a list of atoms, `lat`, ask two questions about it: `(null? lat)` and `else`.
* When recurring on a number, `n`, ask two questions about it: `(zero? n)` and `else`.
* When recurring on a list of S-expressions, `l`, ask three questions about it: `(null? l)`, `(atom? (car l))` and `else`.
====


'''

[[second-commandment]]
=== The Second Commandment

[NOTE,caption=COMMANDMENT]
====
Use `cons` to build lists.
====

'''

[[third-commandment]]
=== The Third Commandment

[NOTE,caption=COMMANDMENT]
====
When building a list, describe the first typical element, and then `cons` it into the natural recursion.
====

'''

[[fourth-commandment-preliminary]]
=== The Fourth Commandment (preliminary)

[NOTE,caption=COMMANDMENT]
====
Always change at least one argument while recurring. It must be changed to be closer to termination. The changing argument must be tested in the termination condition:

* when using `cdr`, test termination with `null?`
====


[[fourth-commandment-rev-1]]
=== The Fourth Commandment (rev. 1)

[NOTE,caption=COMMANDMENT]
====
Always change at least one argument while recurring. It must be changed to be closer to termination. The changing argument must be tested in the termination condition:

* when using `cdr`, test termination with `null?`
* when using `sub1`, test termination with `zero?`
====

[[fourth-commandment-final-version]]
=== The Fourth Commandment (final version)

[NOTE,caption=COMMANDMENT]
====
Always change at least one argument while recurring. When recurring on a list of atoms, `lat', use `(cdr lat)`. When recurring on a number, `n`, use `(sub1 n)`. And when recurring on a list of _S-expressions_, `l`, use `(car l)` and `(cdr l)` if neither `(null? l)` nor `(atom? (car l))` is true.

It must be changed to be closer to termination. The changing argument must be tested in the termination condition:

* when using `cdr`, test termination with `null?`
* when using `sub1`, test termination with `zero?`
====


[[fifth-commandment]]
=== The Fifth Commandment

[NOTE,caption=COMMANDMENT]
====
* When building a value with `o+`, always use `0` (zero) for the value of the terminating line, for adding `0` does not change the value of an addition.
* When building a value with `o*`, always use 1 for the value of the terminating line, for multiplying by `1` (one) does not change the value of a multiplication.
* When building a value with `cons`, always consider `()` for the value of the terminating line.
====

