== » Commandments

[[first-commandment-preliminary]]
=== The First Commandment (preliminary)

[NOTE,caption=COMMANDMENT]
====
Always ask `null?` as the first question in expressing any function.
====

[[first-commandment-rev-1]]
=== The First Commandment (rev. 1)

[NOTE,caption=COMMANDMENT]
====
When recurring on a list of atoms, `lat`, ask two questions about it: `(null? lat)` and `else`.

When recurring on a number, `n`, ask two questions about it: `(zero? n)` and `else`.
====

'''

[[second-commandment]]
=== The Second Commandment

[NOTE,caption=COMMANDMENT]
====
Use `cons` to build lists.
====

'''

[[third-commandment]]
=== The Third Commandment

[NOTE,caption=COMMANDMENT]
====
When building a list, describe the first typical element, and then `cons` it into the natural recursion.
====

'''

[[fourth-commandment-preliminary]]
=== The Fourth Commandment (preliminary)

[NOTE,caption=COMMANDMENT]
====
Always change at least one argument while recurring. It must be changed to be closer to termination. The changing argument must be tested in the termination condition:

* when using `cdr`, test termination with `null?`
====


[[fourth-commandment-rev-1]]
=== The Fourth Commandment (rev. 1)

[NOTE,caption=COMMANDMENT]
====
Always change at least one argument while recurring. It must be changed to be closer to termination. The changing argument must be tested in the termination condition:

* when using `cdr`, test termination with `null?`
* when using `sub1`, test termination with `zero?`
====
