= The Little Schemer
:icons: font
:stem: latexmath
:toc: right
:experimental:

My studies on the book The Little Schemer.

[NOTE]
====
The official repo is the link:https://gitlab.com/devhowto/the-little-schemer[The Litthe Schemer on Gitlab].
The link:https://github.com/devhowto/the-little-schemer[Github repo] is only a mirror.
====

== Chicken Scheme

I'm using link:https://wiki.call-cc.org/man/5/Getting%20started[Chicken Scheme] with the link:http://wiki.call-cc.org/eggref/5/test[test egg] to work on the challenges.

== Tests

Install the link:http://wiki.call-cc.org/eggref/5/test[test egg].

[source,shell-session]
----
$ chicken-install test
----

Run the tests:

[source,shell-session]
----
$ csi -script *.spec.scm
----

== Emacs and Geiser

Install link:https://www.nongnu.org/geiser/[Geiser].
Also see the link:https://wiki.call-cc.org/emacs[Chicken Docs on Setting up Emacs and Geiser]

For Chicken 5, we also need:

[source,shell-session]
----
$ chicken-install apropos chicken-doc srfi-18

$ cd `csi -R chicken.platform -p '(chicken-home)'`
$ curl https://3e8.org/pub/chicken-doc/chicken-doc-repo-5.tgz | sudo tar zx
----

On a buffer containing code/tests, do kbd:[M-x geiser].

kbd:[C-c C-c] will either run tests or evaluate the expression (depends on where in the code _point_ is at the moment).

To run tests in Emacs, open a spec.scm file and evaluate the entire buffer once with kbd:[C-c C-b].
It will evaluate the import and/or load expressions and run the tests once.

Subsequently, it is possible to use kbd:[C-x C-e] to run specific test expressions or 
